export const itemActionTypes = {
  SAVE_ITEM_LOADING: 'SAVE_ITEM_LOADING',
  SAVE_ITEM_SUCCESS: 'SAVE_ITEM_SUCCESS',
  SAVE_ITEM_ERROR: 'SAVE_ITEM_ERROR',

  DELETE_ITEM_LOADING: 'DELETE_ITEM_LOADING',
  DELETE_ITEM_SUCCESS: 'DELETE_ITEM_SUCCESS',
  DELETE_ITEM_ERROR: 'DELETE_ITEM_ERROR',

  UPDATE_ITEM_LOADING: 'UPDATE_ITEM_LOADING',
  UPDATE_ITEM_SUCCESS: 'UPDATE_ITEM_SUCCESS',
  UPDATE_ITEM_ERROR: 'UPDATE_ITEM_ERROR',

  REQUEST_ITEMS_LOADING: 'REQUEST_ITEMS_LOADING', 
  REQUEST_ITEMS_SUCCESS: 'REQUEST_ITEMS_SUCCESS',
  REQUEST_ITEMS_ERROR: 'REQUEST_ITEMS_ERROR',
}