export const itemActionTypes = {
  REQUEST_ITEM: 'REQUEST_ITEM',
  RECEIVE_ITEM: 'RECEIVE_ITEM',
  SAVE_ITEM: 'SAVE_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  ERROR_ITEM: 'ERROR_ITEM',
  REQUEST_ITEMS: 'REQUEST_ITEMS',
  RECEIVE_ITEMS: 'RECEIVE_ITEMS'
}