export const itemActionTypes = {
  ADD_ITEM_LOADING: 'ADD_ITEM_LOADING',
  ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS',
  ADD_ITEM_ERROR: 'ADD_ITEM_ERROR',

  DELETE_ITEM_LOADING: 'DELETE_ITEM_LOADING',
  DELETE_ITEM_SUCCESS: 'DELETE_ITEM_SUCCESS',
  DELETE_ITEM_ERROR: 'DELETE_ITEM_ERROR',

  UPDATE_ITEM_LOADING: 'UPDATE_ITEM_LOADING',
  UPDATE_ITEM_SUCCESS: 'UPDATE_ITEM_SUCCESS',
  UPDATE_ITEM_ERROR: 'UPDATE_ITEM_ERROR',

  GET_ITEMS_LOADING: 'GET_ITEMS_LOADING', 
  GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS',
  GET_ITEMS_ERROR: 'GET_ITEMS_ERROR',
}